version: "3.9"
services:
  ##################################################### MySql #####################################################
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test_docker_db'
      MYSQL_USER: 'momobarro'
      MYSQL_PASSWORD: 'Passer@1'
      MYSQL_ROOT_PASSWORD: 'rootPasser@1'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database:/var/lib/mysql

  ##################################################### phpMyAdmin #####################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST : 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'rootPasser@1'
      MYSQL_ROOT_PASSWORD: 'rootPasser@1'

  ##################################################### Dev ENV #####################################################
  antsbook-dev:
    depends_on:
      - apache
      - db
      - phpmyadmin
    build:
      context: .
    ports:
      - 8082:8080
    volumes:
      - ./logs-srping:/logs
    environment:
      SPRING_ENV: dev
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/test_docker_db'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'rootPasser@1'
#      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'


##################################################### Volumes #####################################################
volumes:
  database: